# Generated by Django 3.2.21 on 2023-11-08 11:46

import core.fields
import core.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0023_alter_jsonext_column_in_tblOfficer'),
        ('insuree', '0026_auto_20230809_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRecord',
            fields=[
                ('id', models.AutoField(db_column='ApiRecordID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='ApiRecordUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('request_date', models.TextField(blank=True, db_column='RequestedData', null=True)),
                ('response_date', models.TextField(blank=True, db_column='ResponseData', null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True, db_column='TimeStamp')),
            ],
            options={
                'db_table': 'tblApiRecord',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ApiUtilitie',
            fields=[
                ('id', models.AutoField(db_column='ApiId', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('access_token', models.TextField(blank=True, db_column='AccessToken', null=True)),
                ('access_TokenExpiry', models.DateTimeField(blank=True, db_column='ExpiryDate', null=True)),
            ],
            options={
                'db_table': 'tblApiUtilitie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaymentServiceProvider',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='PspID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='PspUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('name', models.CharField(db_column='PspName', max_length=50, unique=True)),
                ('account', models.CharField(blank=True, db_column='PspAccount', max_length=36, null=True)),
                ('pin', models.CharField(blank=True, db_column=' PspPin', max_length=128, null=True)),
                ('email', models.EmailField(blank=True, db_column='PspEmail', max_length=100, null=True)),
                ('date_created', models.DateTimeField(blank=True, db_column='DateCreated', default=django.utils.timezone.now)),
                ('is_external_api_user', models.BooleanField(default=False)),
                ('interactive_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.interactiveuser')),
            ],
            options={
                'db_table': 'tblPaymentServiceProviders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='PaymentTransactionId', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='TransactionUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=18)),
                ('psp_transaction_id', models.CharField(blank=True, db_column='PspTransactionID', max_length=125)),
                ('otp', models.CharField(blank=True, db_column='OTP', max_length=10, null=True)),
                ('status', models.BooleanField(blank=True, db_column='PaymentTransactionStatus', default=False)),
                ('json_content', models.JSONField(blank=True, db_column='JsonContent', null=True)),
                ('datetime', models.DateTimeField(blank=True, db_column='Datetime', default=django.utils.timezone.now)),
                ('insuree', models.ForeignKey(blank=True, db_column='InsureeUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_transactions', to='insuree.insuree')),
                ('payment_service_provider', models.ForeignKey(blank=True, db_column='PSPUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_transactions', to='mobile_payment.paymentserviceprovider')),
            ],
            options={
                'db_table': 'tblPaymentTransaction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaymentTransactionMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_transactions', to='core.mutationlog')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='mobile_payment.paymenttransaction')),
            ],
            options={
                'db_table': 'mobilePayment_PaymentTransactionMutation',
                'managed': True,
            },
            bases=(models.Model, core.models.ObjectMutation),
        ),
        migrations.CreateModel(
            name='PaymentServiceProviderMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_service_providers', to='core.mutationlog')),
                ('payment_service_provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='mobile_payment.paymentserviceprovider')),
            ],
            options={
                'db_table': 'mobilePayment_PaymentServiceProviderMutation',
                'managed': True,
            },
            bases=(models.Model, core.models.ObjectMutation),
        ),
    ]
