# Generated by Django 3.2.22 on 2023-10-17 13:25

import core.fields
import core.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0023_alter_jsonext_column_in_tblOfficer'),
        ('insuree', '0013_auto_20211103_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api_Records',
            fields=[
                ('id', models.AutoField(db_column='Api_Record_ID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='Api_Record_UUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('request_date', models.TextField(blank=True, db_column='requested_data', null=True)),
                ('response_date', models.TextField(blank=True, db_column='response_data', null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True, db_column='time_stamp')),
            ],
            options={
                'db_table': 'Api_Records',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Api_Utilities',
            fields=[
                ('id', models.AutoField(db_column='Api_Id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('access_token', models.TextField(blank=True, db_column='access_token', null=True)),
                ('access_TokenExpiry', models.DateTimeField(blank=True, db_column='ExpiryDate', null=True)),
            ],
            options={
                'db_table': 'tblApi_Utilities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaymentServiceProvider',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='Psp_ID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='Psp_UUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('psp_name', models.CharField(db_column='Psp_Name', max_length=50, unique=True)),
                ('psp_username', models.CharField(blank=True, db_column='Psp_Username', max_length=36, null=True)),
                ('psp_password', models.CharField(blank=True, db_column='Psp_Password', max_length=128, null=True)),
                ('psp_account', models.CharField(blank=True, db_column='Psp_Account', max_length=36, null=True)),
                ('psp_pin', models.CharField(blank=True, db_column=' Psp_Pin', max_length=128, null=True)),
                ('email', models.EmailField(blank=True, db_column='Psp_email', max_length=100, null=True)),
                ('access_token', models.CharField(blank=True, db_column='Api_client_access_token', max_length=128, null=True)),
                ('date_created', models.DateTimeField(blank=True, db_column='Date_created', default=django.utils.timezone.now)),
                ('has_login', models.BooleanField(blank=True, db_column='HasLogin', null=True)),
                ('is_external_api_user', models.BooleanField(default=False)),
                ('json_content', models.TextField(blank=True, db_column='Json_content', null=True)),
                ('interactive_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.interactiveuser')),
            ],
            options={
                'db_table': 'tblPaymnet_Service_Provider',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='TransactionId', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='TransactionUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=18)),
                ('transaction_id', models.CharField(blank=True, db_column='transaction_id', max_length=125)),
                ('otp', models.CharField(blank=True, db_column='OTP', max_length=10, null=True)),
                ('status', models.BooleanField(blank=True, db_column='transaction_status', default=False)),
                ('json_content', models.JSONField(blank=True, db_column='Json_content', null=True)),
                ('datetime', models.DateTimeField(blank=True, db_column='Datetime', default=django.utils.timezone.now)),
                ('insuree', models.ForeignKey(blank=True, db_column='InsureeUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='insuree.insuree')),
                ('payment_service_provider', models.ForeignKey(blank=True, db_column='PSPUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='mobile_payment.paymentserviceprovider')),
            ],
            options={
                'db_table': 'tblTransactions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransactionMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='core.mutationlog')),
            ],
            options={
                'db_table': 'TransactionMutation',
                'managed': True,
            },
            bases=(models.Model, core.models.ObjectMutation),
        ),
    ]
