# Generated by Django 3.2.18 on 2023-08-10 17:15

from django.db import migrations

def add_initial_data(mobile_payment, schema_editor):
    ApiUtilities = mobile_payment.get_model('mobile_payment', 'Api_Utilities')
    ApiUtilities.objects.create(name='Qcell_token', access_token="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dnaW5nQXMiOm51bGwsImF1ZCI6WyJBZGFwdGVyX09hdXRoX1Jlc291cmNlX1NlcnZlciJdLCJncmFudF90eXBlIjoicGFzc3dvcmQiLCJkZXZpY2VVbmlxdWVJZCI6bnVsbCwidXNlcl9uYW1lIjoiMTQwMDE1MDIiLCJzY29wZSI6WyJST0xFX0NMSUVOVCJdLCJsYXRpdHVkZSI6bnVsbCwicm9sZUV4dGVybmFsSWQiOm51bGwsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiJdLCJqdGkiOiI5N2FiMTYwNC0yNWU1LTQ4MDYtYjU4MC03NWFhMDgwM2Q2MGQiLCJjbGllbnRfaWQiOiJOSElBX0FDQ0VTU19DSEFOTkVMIiwibG9uZ2l0dWRlIjpudWxsfQ.0L3sJuerv_7mOVUNAYBzmIE8IOhmvaY01meNzRQD-xM", 
                                access_TokenExpiry="2023-08-07 14:58:39.136")
    # Add more data as needed

def reverse_add_initial_data(mobile_payment, schema_editor):
    ApiUtilities = mobile_payment.get_model('mobile_payment', 'Api_Utilities')
    ApiUtilities.objects.filter(name='Qcell_token').delete()

class Migration(migrations.Migration):
    dependencies = [
        ('mobile_payment', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_data, reverse_code=reverse_add_initial_data),
    ]

