# Generated by Django 3.0.3 on 2023-10-17 13:40

from django.db import migrations

def add_initial_data(mobile_payment, schema_editor):
    PaymentServiceProvider = mobile_payment.get_model('mobile_payment', 'PaymentServiceProvider')
    PaymentServiceProvider.objects.create(psp_name='Qmoney', psp_account="14001502", psp_pin="1234")
    # Add more data as needed

def reverse_add_initial_data(mobile_payment, schema_editor):
    PaymentServiceProvider = mobile_payment.get_model('mobile_payment', 'PaymentServiceProvider')
    PaymentServiceProvider.objects.filter(name='Qmoney').delete()



class Migration(migrations.Migration):

    dependencies = [
        ('mobile_payment', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_data, reverse_code=reverse_add_initial_data),
    ]
