# Generated by Django 3.2.18 on 2023-08-24 14:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_payment', '0002_auto_20230810_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api_Client',
            fields=[
                ('id', models.AutoField(db_column='Api_client_ID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='Api_clientUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('password', models.CharField(db_column='Api_client_password', max_length=256)),
                ('login_name', models.CharField(db_column='LoginName', max_length=25, unique=True)),
                ('email', models.EmailField(blank=True, db_column='Api_client_email', max_length=254, null=True)),
                ('access_token', models.CharField(blank=True, db_column='Api_client_access_token', max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Api_Client',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Api_Records',
            fields=[
                ('id', models.AutoField(db_column='Api_Record_ID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='Api_Record_UUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('request_date', models.JSONField(blank=True, db_column='requested_data', null=True)),
                ('response_date', models.JSONField(blank=True, db_column='response_data', null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True, db_column='time_stamp')),
            ],
            options={
                'db_table': 'Api_Records',
                'managed': True,
            },
        ),
    ]
