# Generated by Django 3.2.21 on 2023-11-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_payment', '0002_Qmoney_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='json_content',
            field=models.TextField(blank=True, db_column='JsonContent', null=True),
        ),
    ]
