# Generated by Django 3.2.22 on 2023-10-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_payment', '0002_auto_20231017_1340'),
        ('mobile_payment', '0003_auto_20231017_1617'),
    ]

    operations = [
    ]
