# Generated by Django 3.2.18 on 2023-08-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mobile_payment', '0003_api_client_api_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api_client',
            name='login_name',
        ),
        migrations.AddField(
            model_name='api_client',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='api_clients', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='api_client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='api_client',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='api_client',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='api_client',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='api_client',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='api_clients', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='api_client',
            name='username',
            field=models.CharField(db_column='Api_client_username', default='test_username', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='api_client',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
