# Generated by Django 3.2.18 on 2023-08-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mobile_payment', '0004_auto_20230824_1458'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Api_Client',
            new_name='ApiClient',
        ),
    ]
