# Generated by Django 3.2.21 on 2023-11-01 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_payment', '0004_merge_0002_auto_20231017_1340_0003_auto_20231017_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentserviceprovider',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='paymentserviceprovider',
            name='has_login',
        ),
        migrations.RemoveField(
            model_name='paymentserviceprovider',
            name='psp_password',
        ),
        migrations.RemoveField(
            model_name='paymentserviceprovider',
            name='psp_username',
        ),
    ]
