# Generated by Django 3.2.18 on 2023-08-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_payment', '0005_rename_api_client_apiclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmutation',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='PaymentServiceProvider',
        ),
        migrations.DeleteModel(
            name='ApiClient',
        ),
    ]
