# Generated by Django 3.2.23 on 2024-01-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_payment', '0005_paymentserviceprovider_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiUtilitie',
        ),
    ]
