# Generated by Django 3.2.18 on 2023-08-29 15:03

import core.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0021_set_managed_to_true'),
        ('mobile_payment', '0006_auto_20230829_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentServiceProvider',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(db_column='PSP_ID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='PSPUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('psp_name', models.CharField(blank=True, db_column='PSPName', max_length=50, null=True)),
                ('psp_account', models.CharField(db_column='PSPAccount', max_length=36)),
                ('pin', models.CharField(db_column=' PSPPin', max_length=128)),
                ('email', models.EmailField(blank=True, db_column='PSP_email', max_length=254, null=True)),
                ('access_token', models.CharField(blank=True, db_column='Api_client_access_token', max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='api_clients', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='api_clients', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'tblPaymnet_Service_Provider',
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='Insuree',
            new_name='insuree',
        ),
        migrations.CreateModel(
            name='PaymentServiceProviderMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_service_provider', to='core.mutationlog')),
                ('payment_service_provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='mobile_payment.paymentserviceprovider')),
            ],
            options={
                'db_table': 'PaymentServiceProviderMutation',
                'managed': True,
            },
            bases=(models.Model, core.models.ObjectMutation),
        ),
        migrations.AddField(
            model_name='transactions',
            name='payment_service_provider',
            field=models.ForeignKey(blank=True, db_column='PSPUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='mobile_payment.paymentserviceprovider'),
        ),
    ]
