# Generated by Django 3.2.18 on 2023-08-30 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_payment', '0007_auto_20230829_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentserviceprovider',
            old_name='is_staff',
            new_name='is_external_api_user',
        ),
        migrations.RemoveField(
            model_name='paymentserviceprovider',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='paymentserviceprovider',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='paymentserviceprovider',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='paymentserviceprovider',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='paymentserviceprovider',
            name='password',
        ),
        migrations.RemoveField(
            model_name='paymentserviceprovider',
            name='user_permissions',
        ),
    ]
