# Generated by Django 3.2.18 on 2023-08-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_payment', '0008_auto_20230830_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentserviceprovider',
            name='pin',
        ),
        migrations.AddField(
            model_name='paymentserviceprovider',
            name='psp_password',
            field=models.CharField(blank=True, db_column='Psp_Password', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='paymentserviceprovider',
            name='psp_pin',
            field=models.CharField(blank=True, db_column=' PSPPin', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='paymentserviceprovider',
            name='psp_username',
            field=models.CharField(blank=True, db_column='Psp_Username', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='paymentserviceprovider',
            name='psp_account',
            field=models.CharField(blank=True, db_column='PSPAccount', max_length=36, null=True),
        ),
    ]
