# Generated by Django 3.2.18 on 2023-08-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_payment', '0009_auto_20230830_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentserviceprovider',
            name='is_external_api_user',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
