# Generated by Django 3.2.18 on 2023-08-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_payment', '0010_alter_paymentserviceprovider_is_external_api_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentserviceprovider',
            name='email',
            field=models.EmailField(blank=True, db_column='PSP_email', max_length=50, null=True),
        ),
    ]
