# Generated by Django 3.2.18 on 2023-08-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_payment', '0011_alter_paymentserviceprovider_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentserviceprovidermutation',
            name='mutation',
        ),
        migrations.RemoveField(
            model_name='paymentserviceprovidermutation',
            name='payment_service_provider',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='payment_service_provider',
        ),
        migrations.DeleteModel(
            name='PaymentServiceProvider',
        ),
        migrations.DeleteModel(
            name='PaymentServiceProviderMutation',
        ),
    ]
