# Generated by Django 3.2.18 on 2023-08-30 21:06

import core.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_payment', '0012_auto_20230830_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentServiceProvider',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='Psp_ID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='Psp_UUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('psp_name', models.CharField(db_column='Psp_Name', max_length=50, unique=True)),
                ('psp_username', models.CharField(blank=True, db_column='Psp_Username', max_length=36, null=True)),
                ('psp_password', models.CharField(blank=True, db_column='Psp_Password', max_length=36, null=True)),
                ('psp_account', models.CharField(blank=True, db_column='Psp_Account', max_length=36, null=True)),
                ('psp_pin', models.CharField(blank=True, db_column=' Psp_Pin', max_length=128, null=True)),
                ('email', models.EmailField(blank=True, db_column='Psp_email', max_length=100, null=True)),
                ('access_token', models.CharField(blank=True, db_column='Api_client_access_token', max_length=100, null=True)),
                ('date_created', models.DateTimeField(blank=True, db_column='Date_created', default=django.utils.timezone.now)),
                ('is_external_api_user', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'db_table': 'tblPaymnet_Service_Provider',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='transactions',
            name='payment_service_provider',
            field=models.ForeignKey(blank=True, db_column='PSPUUID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='mobile_payment.paymentserviceprovider'),
        ),
    ]
