# Generated by Django 3.2.18 on 2023-08-31 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_payment', '0014_alter_paymentserviceprovider_is_external_api_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='payment_service_provider',
        ),
        migrations.DeleteModel(
            name='PaymentServiceProvider',
        ),
    ]
