# Generated by Django 3.2.18 on 2023-09-06 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_set_managed_to_true'),
        ('mobile_payment', '0017_auto_20230831_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentserviceprovider',
            name='technical_user',
            field=models.ForeignKey(blank=True, db_column='Technical_User', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_service_provider', to='core.technicaluser'),
        ),
    ]
