# Generated by Django 3.2.18 on 2023-09-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_payment', '0019_remove_paymentserviceprovider_technical_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentserviceprovider',
            name='has_login',
            field=models.BooleanField(blank=True, db_column='HasLogin', null=True),
        ),
    ]
