# Generated by Django 3.2.21 on 2023-09-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_payment', '0020_paymentserviceprovider_has_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentserviceprovider',
            name='json_content',
            field=models.TextField(blank=True, db_column='Json_content', null=True),
        ),
    ]
