# Generated by Django 3.2.21 on 2023-09-29 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_user_psp_admin'),
        ('mobile_payment', '0021_paymentserviceprovider_json_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentserviceprovider',
            name='interactive_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.interactiveuser'),
        ),
    ]
